version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: airquality
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schemas:/docker-entrypoint-initdb.d/schemas
      - ./db/functions:/docker-entrypoint-initdb.d/functions
    command: postgres -c shared_preload_libraries=timescaledb

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  air-quality-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload

  streamlit-ui:
    build: .
    ports:
      - "8501:8501"
    environment:
      - API_ENDPOINT=http://air-quality-api:8000
    depends_on:
      - air-quality-api
    volumes:
      - .:/app
    command: streamlit run src/ui/streamlit_app.py --server.port 8501 --server.address 0.0.0.0

volumes:
  postgres_data:
  redis_data: